In [1]:
!pip install numpy


In [4]:
import numpy as np
# creating array
arr1=np.array([1,2,2,3]) # one dimenssion on more correct only having 4 elements no any concepts of rows and columns
print(arr1)
print(type(arr1))
arr1.shape

[1 2 2 3]
<class 'numpy.ndarray'>


(4,)

In [7]:
arr2=np.array([1,2,2,3])
arr2.reshape(1,4) # note= this will definetly make it 1,4 but on on finding shape of arr2 i will again got (4,) mean arr2 having 4 elemets


array([[1, 2, 2, 3]])

In [11]:
print(arr2.shape)

(4,)


In [10]:
arr3=np.array([[1,4,7]]) # now this is completly can be refer as the (1,3)
arr3.shape

(1, 3)

In [12]:
# 2d array
arr3=np.array([[1,4,7],[2,5,8]]) # now this is completly can be refer as the (2,3)
print(arr3)
arr3.shape

[[1 4 7]
 [2 5 8]]


(2, 3)

In [ ]:
# some of the inbuilt function in numpy array

In [24]:
np.arange(0,10,2) # (start,end not included,step size)


array([0, 2, 4, 6, 8])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.eye(3) # creation of identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# numpy vectorizes operations


In [28]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
# elements wise addition
print("addition",arr1+arr2)
# elements wise substraction
print("substraction",arr1-arr2)
# elements wise multiplication
print("multiplication",arr1*arr2)
# elements wise division
print("division",arr1/arr2)


addition [5 7 9]
substraction [-3 -3 -3]
multiplication [ 4 10 18]
division [0.25 0.4  0.5 ]


In [ ]:
# some universal functions

In [30]:
arr=np.array([1,4,9,16,25])
# square root
print(np.sqrt(arr))
# exponential
print(np.exp(arr))
# log
print(np.log(arr))
# sin
print(np.sin(arr))


[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [ ]:
# slicing and indexing over numpy array

In [47]:
arr=([[1,2,3],[4,5,6],[7,8,9]])
# note= indexing always starts from zero
print("array:\n",arr)# array
print(arr[0][0]) # first element
print(arr[[0][0]])# first row

array:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
1
[1, 2, 3]


In [52]:
# array elements can be modified
# some prectical implimentation related to the array

In [53]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
print(mean)
std_dev=np.std(data)
print(std_dev)
normalize_data=(data-mean)/std_dev
print(normalize_data) # data normaization mean making mean= 0 and std_dev=1


3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [55]:
# measure of centerality
arr=np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

3.0
3.0
1.4142135623730951
2.0


In [64]:
#some logical operations
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr>5)
print(arr[arr>5])
print(arr[(arr>=3) & (arr<=8)])



[False False False False False  True  True  True  True]
[6 7 8 9]
[3 4 5 6 7 8]
